config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  namespace :admin do
    resources :customers,only: [:index,:show,:edit,:update]
  	resources :products,only: [:index,:new,:create,:show,:edit,:update,]
  	get 'top'=>'products#top'
  	resources :genres,only: [:index,:create,:edit,:update,:show]
  	resources :orders,only: [:index,:show,:update] do
  	  member do
        get :current_index
        resource :order_details,only: [:update]
      end
      collection do
        get :today_order_index
      end
    end
  end

  devise_for :customers,:controllers => {
      :sessions => "customers/sessions",
      :registrations => "customers/registrations",
      :passwords => "customers/passwords"
    }

  get 'about' => 'customers/products#about'
  root 'customers/products#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope module: :customers do
    resources :products,only: [:index,:show]
    get 'customer/edit' => 'customers#edit'
    put 'customer' => 'customers#update'

  	resource :customers,only: [:show] do
  		collection do
  	     get 'leave'
  	     patch 'out'
  	  end


      resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end



      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post 'log'
          get 'thanx'
        end
      end

      resources :addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :orders, dependent: :destroy

  #フルネームメソッド
  def full_name
    self.last_name + self.first_name
  end

  #フルネームカナメソッド
  def kana_full_name
    self.kana_last_name + self.kana_first_name
  end


  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :kana_first_name, presence: true
  validates :kana_last_name, presence: true
  validates :postal_code, presence: true, numericality: { only_integer: true }, length: { is: 7 }
  validates :street_address, presence: true
  validates :phone_number, presence: true, numericality: { only_integer: true }

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

	def show
		@customer = Customer.find(params[:id])
	end

	def edit
		@customer = Customer.find(params[:id])
	end

	def update
	@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
		   flash[:success] = "会員情報を変更しました"
		   redirect_to admin_customer_path
		else
			render "edit"
		end

	end

	private
	def customer_params
	  params.require(:customer).permit(
	  	:first_name,
	  	:last_name,
	  	:kana_first_name,
	  	:kana_last_name,
	  	:postal_code,
	  	:street_address,
	  	:phone_number,
	  	:email,
	  	:is_valid)
	end
end

app/controllers/customers/addresses_controller.rb
class Customers::AddressesController < ApplicationController
  before_action :authenticate_customer!

  def index
    @address = Address.new
    @addresses = current_customer.addresses

  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    @addresses = current_customer.addresses

    if @address.save
      flash[:notice] = "配送先を登録しました！"
      redirect_to customers_addresses_path
    else
      render :index
    end
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    flash[:alert] = "配送先を削除しました。"
    redirect_to customers_addresses_path
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    if @address.update(address_params)
      flash[:notice] = "配送先情報を変更しました。"
      redirect_to customers_addresses_path
    else
      render :edit
    end
  end

  private

	def address_params
  	 params.require(:address).permit(:postal_code, :address, :name)
  end
end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
  include ApplicationHelper

  before_action :authenticate_customer!
  before_action :baria_user, only: [:update, :destroy]

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(quantity: params[:cart_item][:quantity].to_i)
    flash[:notice] = "#{@cart_item.product.name}の数量を変更しました。"
    redirect_to customers_cart_items_path
  end

  def create
    @cart_item = current_customer.cart_items.new(params_cart_item)
    @update_cart_item = CartItem.find_by(product: @cart_item.product)
    if @update_cart_item.present? && @cart_item.valid?
      @cart_item.quantity += @update_cart_item.quantity
      @update_cart_item.destroy
    end
    if  @cart_item.save
      flash[:notice] = "#{@cart_item.product.name}をカートに追加しました。"
      redirect_to customers_cart_items_path
    else
      @product = Product.find(params[:cart_item][:product_id])
      @cart_item = CartItem.new
      flash[:notice] = "個数を選択してください。"
      render "customers/products/show"
    end
  end

  def index
    @cart_items = current_customer.cart_items
    @sum = 0
    @cart_items.each do |cart_item|
      @total = (Product.find(cart_item.product_id).price * 1.1 * cart_item.quantity).to_i
      @sum += @total
    end
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    flash[:alert] = "#{@cart_item.product.name}を削除しました。"
    redirect_to customers_cart_items_path
  end

  def all_destroy
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    flash[:alert] = "カートの商品を全て削除しました。"
    redirect_to customers_cart_items_path
  end

  private

  def params_cart_item
    params.require(:cart_item).permit(:quantity, :product_id)
  end

  def baria_user
    unless CartItem.find(params[:id]).customer.id.to_i == current_customer.id
      redirect_to customers_customer_path
    end
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
  before_action :authenticate_customer!, only: [:show, :edit, :update, :leave, :out]
  before_action :rule_path, only: [:rule]

  def show
    @customer = current_customer
  end
  
  def leave
    @custmoer = current_customer
  end
  
  def out
    @customer = current_customer
    @custmoer.update(is_deleted: true)
    reset_section
    flash[:alert] = "退会が完了しました"
    redirect_to top_path
  end
  
  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    if @customer.update(customer_params)
      falsh[:notice] = "会員情報を更新しました！"
      redirect_to customer_customer_path
    else
      render :edit
    end
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :postal_code, :address, :phone_number)
  end
  
end

app/controllers/customers/customoer_controller.rb
class Customers::CustomoerController < ApplicationController
  
  def show
  end
  
  def withdrawal
  end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
  include ApplicationHelper

  before_action :to_log, only: [:show]
  before_action :authenticate_customer!

  def new
  	@order = Order.new
  	@addresses = Address.where(customer: current_customer)
  end

	def log
    @cart_items = current_customer.cart_items
		@order = Order.new(
      customer: current_customer,
      payment_method: params[:order][:payment_method]
    )
    @order.total_price = billing(@order)


    if params[:order][:addresses] == "residence"
      @order.postal_code = current_customer.postal_code
      @order.shipping_address     = current_customer.street_address
      @order.name        = current_customer.last_name +
                           current_customer.first_name

    elsif params[:order][:addresses] == "addresses"
      ship = Address.find(params[:order][:address_id])
      @order.postal_code = ship.postal_code
      @order.shipping_address     = ship.address
      @order.name        = ship.name

    # addressにnew_addressの値がはいっていれば
    elsif params[:order][:addresses] == "new_address"
      @order.postal_code = params[:order][:postal_code]
      @order.shipping_address     = params[:order][:shipping_address]
      @order.name        = params[:order][:name]
      @ship = "1"

      # バリデーションがあるならエラーメッセージを表示
      unless @order.valid? == true
        @addresses = Address.where(customer: current_customer)
        render :new
      end
    end
	end

	def create
    @order = current_customer.orders.new(order_params)
    @order.save
    flash[:notice] = "ご注文が確定しました。"
    redirect_to thanx_customers_orders_path

    # もし情報入力でnew_addressの場合Addressに保存
    if params[:order][:ship] == "1"
      current_customer.addresses.create(address_params)
    end

    # カート商品の情報を注文商品に移動
    @cart_items = current_cart
    @cart_items.each do |cart_item|
    OrderDatail.create(
      product:  cart_item.product,
      order:    @order,
      quantity: cart_item.quantity,
      subprice: sub_price(cart_item)
    )
    end
    # 注文完了後、カート商品を空にする
    @cart_items.destroy_all
	end

	def thanx
	end

	def index
    @orders = current_customer.orders
	end

	def show
	  @order = Order.find(params[:id])
    @order_datails = @order.order_datails
	end

  private
  def order_params
    params.require(:order).permit(:postal_code, :shipping_address, :name, :payment_method, :total_price)
  end

  def address_params
    params.require(:order).permit(:postal_code, :address, :name)
  end

  def to_log
    redirect_to customers_cart_items_path if params[:id] == "log"
  end

end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/products_controller.rb
class Customers::ProductsController < ApplicationController
  before_action :authenticate_customer!, only: [:show]

  def top
    @products = Product.all.order(created_at: :asc)
    @genres = Genre.all
  end

  def index
    @genres = Genre.all
    @products = Product.all.page(params[:page]).per(8)
  end

  def show
    @products = Product.all
    @product = Product.find(params[:id])
    @cart_item = CartItem.new
  end

  def about
  end


  private

  def product_params
    params.require(:product).permit(:name, :price, :introduction, :image_id, :is_active, :genre_id)
  end

end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers/addresses_helper.rb
module Customers::AddressesHelper
end

app/helpers/customers/cart_items_helper.rb
module Customers::CartItemsHelper
end

app/helpers/customers/customers_helper.rb
module Customers::CustomersHelper
end

app/helpers/customers/customoer_helper.rb
module Customers::CustomoerHelper
end

app/helpers/customers/homes_helper.rb
module Customers::HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="admin-customer-edit pt-5">
    <h4 class="pb-3"><%= @customer.full_name %>さんの会員情報編集</h4>
    <%= form_with(model: @customer, url: admin_customer_path(@customer), local: true) do |f| %>
      <table class="w-100 admin-customer-show">
        <tr class="row pb-3">
          <td class="col-md-2">会員ID</td>
          <td class="col-md-10"><%= @customer.id %></td>
        </tr>
        <tr class="row pb-3">
          <td class="col-md-2">氏名</td>
          <td class="col-md-10">
            <%= f.text_field :last_name, class: "mr-4" %>
            <%= f.text_field :first_name %>
          </td>
        </tr>
        <tr class="row pb-3">
          <td class="col-md-2">フリガナ</td>
          <td class="col-md-10">
            <%= f.text_field :kana_last_name, class: "mr-4" %>
            <%= f.text_field :kana_first_name %>
          </td>
        </tr>
        <tr class="row pb-3">
          <td class="col-md-2">郵便番号</td>
          <td class="col-md-10">
            <%= f.text_field :postal_code %>
          </td>
        </tr>
        <tr class="row pb-3">
          <td class="col-md-2">住所</td>
          <td class="col-md-6">
            <%= f.text_field :street_address, class: "w-100" %>
          </td>
        </tr>
        <tr class="row pb-3">
          <td class="col-md-2">電話番号</td>
          <td class="col-md-10">
            <%= f.text_field :phone_number %>
          </td>
        </tr>
        <tr class="row pb-3">
          <td class="col-md-2">メールアドレス</td>
          <td class="col-md-10">
            <%= f.email_field :email %>
          </td>
        </tr>
        <tr class="row pb-3">
          <td class="col-md-2">会員ステータス</td>
          <td class="col-md-10">
            <span class="admin-is_deleted-radio_button mr-3">
              <%= f.radio_button :is_deleted, true %>
              <%= f.label :is_deleted, '無効', value: true %>
            </span>
            <span class="admin-is_deleted-radio_button">
              <%= f.radio_button :is_deleted, false %>
              <%= f.label :is_deleted, '有効', value: false %>
            </span>
          </td>
        </tr>
        <tr class="row pb-3">
          <td class="col-md-2"></td>
          <td class="col-md-10">
            <%= f.submit "変更を保存", class: "btn btn-success" %>
          </td>
        </tr>
      </table>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="admin-customer pt-5">
    <h4 class="pb-3">会員一覧</h4>
    <table class="table">
      <tr class="table-active">
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
      <% @customers.each do |customer| %>
        <tr>
          <td>
            <%= customer.id %>
          </td>
          <td>
            <%= link_to customer.full_name, admin_customer_path(customer), class: "text-dark" %>
          </td>
          <td>
            <%= customer.email %>
          </td>
          <td>
            <% if customer.is_deleted == true %>
              <p class="text-secondary">退会済</p>
            <% else %>
              <p class="text-success">有効</p>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>

    <div class="pagenate">
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="admin-customer-show pt-5">
    <h4 class="pb-3"><%= @customer.full_name %>さんの会員詳細</h4>
    <table class="w-100 admin-customer-show">
      <tr class="row pb-3">
        <td class="col-md-2">会員ID</td>
        <td class="col-md-10"><%= @customer.id %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">氏名</td>
        <td class="col-md-10"><%= @customer.full_name %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">フリガナ</td>
        <td class="col-md-10"><%= @customer.kana_full_name %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">郵便番号</td>
        <td class="col-md-10"><%= @customer.postal_code %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">住所</td>
        <td class="col-md-10"><%= @customer.street_address %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">電話番号</td>
        <td class="col-md-10"><%= @customer.phone_number %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">メールアドレス</td>
        <td class="col-md-10"><%= @customer.email %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">会員ステータス</td>
        <td class="col-md-10">
          <% if @customer.is_deleted == true %>
            <p class="text-secondary">退会済</p>
          <% else %>
            <p class="text-success">有効</p>
          <% end %>
        </td>
      </tr>
      <tr class="row">
        <td class="col-md-2"></td>
        <td class="col-md-10">
          <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success mr-5", type: "button" %>
          <%= link_to "注文履歴一覧を見る", admin_orders_path, class: "btn btn-info", type: "button" %>
        </td>
      </tr>
    </table>
  </div>
</div>