config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  namespace :admin do
    resources :customers,only: [:index,:show,:edit,:update]
  	resources :products,only: [:index,:new,:create,:show,:edit,:update,]
  	get 'top'=>'products#top'
  	resources :genres,only: [:index,:create,:edit,:update,:show]
  	resources :orders,only: [:index,:show,:update] do
  	  member do
        get :current_index
        resource :order_details,only: [:update]
      end
      collection do
        get :today_order_index
      end
    end
  end

  devise_for :customers,:controllers => {
      :sessions => "customers/sessions",
      :registrations => "customers/registrations",
      :passwords => "customers/passwords"
    }

  get 'about' => 'customers/products#about'
  root 'customers/products#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope module: :customers do
    resources :products,only: [:index,:show]
    get 'customer/edit' => 'customers#edit'
    put 'customer' => 'customers#update'

  	resource :customers,only: [:show] do
  		collection do
  	     get 'leave'
  	     patch 'out'
  	  end


      resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end



      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post 'log'
          get 'thanx'
        end
      end

      resources :addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

	validates :customer_id, :name, :address, presence: true
	validates :postal_code, length: {is: 7}, numericality: { only_integer: true }

	# order/newで使用
	def order_address
		self.postal_code + self.address + self.name
	end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :product
  belongs_to :customer

  validates :customer_id, :product_id, :quantity, presence: true
	validates :quantity, numericality: { only_integer: true }

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :orders, dependent: :destroy

  #フルネームメソッド
  def full_name
    self.last_name + self.first_name
  end

  #フルネームカナメソッド
  def kana_full_name
    self.kana_last_name + self.kana_first_name
  end


  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :kana_first_name, presence: true
  validates :kana_last_name, presence: true
  validates :postal_code, presence: true, numericality: { only_integer: true }, length: { is: 7 }
  validates :street_address, presence: true
  validates :phone_number, presence: true, numericality: { only_integer: true }

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products
  
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
	has_many :order_datails, dependent: :destroy

	validates :customer_id, :shipping_address,:name, :postage,
			  		:total_price, :payment_method,
			  		presence: true
	validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
	validates :postage, :total_price, numericality: { only_integer: true }

	enum payment_method: {"クレジットカード": 0,"銀行振込": 1}
	enum order_status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送準備中": 3, "発送済み": 4}


end

app/models/order_datail.rb
class OrderDatail < ApplicationRecord
  belongs_to :order
	belongs_to :product

	validates :product_id, :order_id, :quantity,
			  		:subprice, presence: true
	validates :subprice, :quantity, numericality: { only_integer: true }

	enum produciton_status: {"着手不可": 0,"製作待ち": 1,"製作中": 2,"製作完了": 3}
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :orders, through: :order_details
  has_many :order_details

  attachment :image

	validates :genre_id, :name, :price, presence: true
	validates :introduction, length: {maximum: 200}
	validates :price, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
   before_action :authenticate_admin!, except: [:show]

  def index
    @genre = Genre.new
    @genres = Genre.all.page(params[:page]).per(10)
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
       flash[:notice] = "ジャンルを追加しました"
       redirect_to admin_genres_path
    else
      @genres = Genre.all.page(params[:page]).per(10)
      render :index and return
    end
  end

  def show
    @products = Product.all.all.page(params[:page]).per(10)
    @genre = Genre.find(params[:id])
    @genres = @genre.products.order(created_at: :desc).all.page(params[:page]).per(5)
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
       flash[:notice] = "You have update Genre successfully"
       redirect_to admin_genres_path
    else
       render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name, :is_valid)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    # ログイン時のパスを変更してる
    def after_sign_in_path_for(resource)
      if customer_signed_in?
        customers_path(resource)
      else
        admin_top_path
      end
    end

    #ログアウト時のパスの変更
    def after_sign_out_path_for(resource)
      root_path
    end

    # 新規登録の保存機能
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,
  			 keys: [:first_name, :last_name, :kana_first_name, :kana_last_name,
                :email, :postal_code, :street_address, :phone_number])

      #sign_upの際にnameのデータ操作を許。追加したカラム。
  		devise_parameter_sanitizer.permit(:sign_in, keys: [:email])

    end

  private

  # before_action作成

  def set_product
    @product = Product.find(params[:id])
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def set_cart_item
    @cart_item = CartItem.find(params[:id])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_cart
    @cart_items = current_customer.cart_items
  end

  # 小数点切り捨てはfloor,３桁区切りはto_s(:delimited)
  # 税込の計算
  def tax_price(price)
    (price * 1.1).floor
  end

  # 小計の計算
  def sub_price(sub)
    (tax_price(sub.product.price) * sub.quantity)
  end

  # 合計金額の計算
  def total_price(totals)
    price = 0
    totals.each do |total|
      price  +=  sub_price(total)
    end
    return price
  end

  # 請求額の計算
  def billing(order)
    total_price(current_cart) + order.postage
  end
end

app/helpers/customers/addresses_helper.rb
module Customers::AddressesHelper
end

app/helpers/customers/customers_helper.rb
module Customers::CustomersHelper
end

app/helpers/customers/homes_helper.rb
module Customers::HomesHelper
end

app/helpers/customers/orders_helper.rb
module Customers::OrdersHelper
end

app/helpers/customers/products_helper.rb
module Customers::ProductsHelper
end

app/views/admin/genres/edit.html.erb
<% provide(:title, "ジャンル編集") %>
<h2 class="head-line title_h2 text-center" >ジャンル編集</h2>

  <% if @genre.errors.any? %>
    <%= render "layouts/error_messages", resource: @genre %>
  <% end %>
  <%= form_for @genre, :url => {:action => :update} do |f| %>
  <div>
    ジャンル
      <%= f.text_field :name  %>
      <%= f.radio_button :is_valid, true %>
      <%= f.label :is_valid, "有効", {value: :true, style: "display: inline-block;"} %>
      <%= f.radio_button :is_valid, false %>
      <%= f.label :is_valid, "無効", {value: :false, style: "display: inline-block;"} %>
      <%= f.submit "変更を保存する", class: "btn btn-info" %>
    </div>
  <% end %>
<br>
  <div class="col-xs-12">
    <%= link_to "戻る", admin_genres_path, class: "glyphicon glyphicon-home btn btn-info" %>
  </div>

app/views/admin/genres/index.html.erb
<% provide(:title, "ジャンル一覧・追加") %>
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h2 class="head-line title_h2 text-center">ジャンル一覧・追加</h2>
        <%= form_for @genre, :url => {:action => :create} do |f| %>
          <%= render "layouts/error_messages", resource: @genre %>
          <div class="col-xs-offset-1">
            <i class="fas fa-candy-cane"></i>ジャンル
            <%= f.text_field :name  %>
              <%= f.radio_button :is_valid, true %>
              <%= f.label :is_valid, "有効", {value: :true, style: "display: inline-block;"} %>
              <%= f.radio_button :is_valid, false %>
              <%= f.label :is_valid, "無効", {value: :false, style: "display: inline-block;"} %>
            <%= f.submit "追加", class: "btn btn-info" %>
          </div>
        <% end %>
      <div class="col-xs-8 col-xs-offset-2">
        <table class="table table-hover table-inverse table-bordered">
          <thead>
            <tr class="info">
              <th>ジャンル</th>
              <th>状態</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @genres.each do |genre| %>
              <tr>
                <td class="text-left"><%= genre.name%></td>
  
                <% if genre.is_valid == true %>
                  <td class="genre-td"><i class="fas fa-bullseye red"></i>有効</td>
                <% elsif genre.is_valid == false %>
                  <td class="genre-td"><i class="fas fa-bullseye blue"></i>無効</td>
                <% end %>
                <td class="genre-td"><%= link_to "編集する", edit_admin_genre_path(genre), class: "glyphicon glyphicon-pencil btn btn-success" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
      <div class= "text-center"><%= paginate(@genres) %></div>
  </div>
</div>

app/views/admin/genres/show.html.erb
<% provide(:title, "#{@genre.name}一覧") %>
<h2 class="product-headlinehead-line title_h2 text-center"><%= @genre.name %>一覧</h2>
</span>
<div class="row">
  <div class="col-xs-3 product-index">
    <%= render "layouts/genre_search", products: @products %>
  </div>
  <div class="col-xs-9 product-index">
      <div class="clearfix product-box">
        <% @genres.first(6).each do |product| %>
          <%= render "customer/products/product_each", product: product %>
        <% end %>
      </div>
     <div class="text-center"><%= paginate(@genres) %></div>
  </div>

</div>