config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  namespace :admin do
    resources :customers,only: [:index,:show,:edit,:update]
  	resources :products,only: [:index,:new,:create,:show,:edit,:update,]
  	get 'top'=>'products#top'
  	resources :genres,only: [:index,:create,:edit,:update,:show]
  	resources :orders,only: [:index,:show,:update] do
  	  member do
        get :current_index
        resource :order_details,only: [:update]
      end
      collection do
        get :today_order_index
      end
    end
  end

  devise_for :customers,:controllers => {
      :sessions => "customers/sessions",
      :registrations => "customers/registrations",
      :passwords => "customers/passwords"
    }

  get 'about' => 'customers/products#about'
  root 'customers/products#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope module: :customers do
    resources :products,only: [:index,:show]
    get 'customer/edit' => 'customers#edit'
    put 'customer' => 'customers#update'

  	resource :customers,only: [:show] do
  		collection do
  	     get 'leave'
  	     patch 'out'
  	  end


      resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end



      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post 'log'
          get 'thanx'
        end
      end

      resources :addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :orders, through: :order_details
  has_many :order_details

  attachment :image

	validates :genre_id, :name, :price, presence: true
	validates :introduction, length: {maximum: 200}
	validates :price, numericality: { only_integer: true }
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update]
  before_action :set_genres, only: [:new, :edit, :index, :create, :update]
  before_action :authenticate_admin!

  def top
    now = Time.current
    @orders = Order.where(created_at: now.all_day)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "新商品を登録しました"
      redirect_to admin_product_path(@product)
    else
      render :new
    end
  end

  def index
    @products = Product.all.page(params[:page]).per(10)
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    if @product.update(product_params)
      flash[:success] = "商品内容をを変更しました"
      redirect_to admin_product_path(@product)
    else
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :image, :introduction,
       :genre_id, :price, :is_active)
  end

  def set_genres
    @genres = Genre.where(is_active: true)
  end

end

app/controllers/customers/products_controller.rb
class Customers::ProductsController < ApplicationController
  before_action :authenticate_customer!, only: [:show]

  def top
    @products = Product.all.order(created_at: :asc)
    @genres = Genre.all
  end

  def index
    @genres = Genre.all
    @products = Product.all.page(params[:page]).per(8)
  end

  def show
    @products = Product.all
    @product = Product.find(params[:id])
    @cart_item = CartItem.new
  end

  def about
  end


  private

  def product_params
    params.require(:product).permit(:name, :price, :introduction, :image_id, :is_active, :genre_id)
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/customers/products_helper.rb
module Customers::ProductsHelper
end

app/views/admin/products/_form_products.html.erb
<div class="form-group row">
    <p class="col-md-5">商品画像</p>
    <%= f.attachment_field :image, class: 'image col-md-7 p-0' %>
  </div>
  <div class="form-group row">
    <%= f.label :"商品名", class: "col-sm-5 control-label" %>
    <%= f.text_field :name, class: "col-sm-7 form-control-static name" %>
  </div>
  <div class="form-group row">
    <%= f.label :"商品説明", class: "col-sm-5 control-label" %>
    <%= f.text_area :introduction, class: "col-sm-7 control-label explanation" %>
  </div>
  <div class="form-group row">
    <%= f.label :"ジャンル", class: "col-sm-5 control-label" %>
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, prompt: "-- 選択してください --", class: "col-sm-7 genre_id") %>
  </div>
  <div class="form-group row">
    <%= f.label :"税抜価格", class: "col-sm-5 control-label" %>
    <%= f.text_field :price, class: "col-sm-6 form-control-static tax_out_price mr-2" %>円
  </div>
  <div class="form-group row radio_button">
    <%= f.label :"販売ステータス", class: "col-sm-5 control-label" %>
    <%= f.radio_button :is_active, true %>
    <%= f.label :is_active, "販売中", value: :true %>
    <%= f.radio_button :is_active, false, class: "ml-3" %>
    <%= f.label :is_active, "販売停止中", value: :false %>
  </div>

app/views/admin/products/_from_products.html.erb
<div class="form-group row">
    <p class="col-md-5">商品画像</p>
    <%= f.attachment_field :image, class: 'image col-md-7 p-0' %>
  </div>
  <div class="form-group row">
    <%= f.label :"商品名", class: "col-sm-5 control-label" %>
    <%= f.text_field :name, class: "col-sm-7 form-control-static name" %>
  </div>
  <div class="form-group row">
    <%= f.label :"商品説明", class: "col-sm-5 control-label" %>
    <%= f.text_area :introduction, class: "col-sm-7 control-label explanation" %>
  </div>
  <div class="form-group row">
    <%= f.label :"ジャンル", class: "col-sm-5 control-label" %>
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, prompt: "-- 選択してください --", class: "col-sm-7 genre_id") %>
  </div>
  <div class="form-group row">
    <%= f.label :"税抜価格", class: "col-sm-5 control-label" %>
    <%= f.text_field :price, class: "col-sm-6 form-control-static tax_out_price mr-2" %>円
  </div>
  <div class="form-group row radio_button">
    <%= f.label :"販売ステータス", class: "col-sm-5 control-label" %>
    <%= f.radio_button :is_active, true %>
    <%= f.label :is_active, "販売中", value: :true %>
    <%= f.radio_button :is_active, false, class: "ml-3" %>
    <%= f.label :is_active, "販売停止中", value: :false %>
  </div>

app/views/admin/products/edit.html.erb
<div class="text-danger">
<% if @product.errors.any? %>
   <span class="h4"><%= @product.errors.count %>errors prohibited this obj from being saved:</span>
  <% @product.errors.full_messages.each do |message| %><br>
     ・<%= message %>
  <% end %>
<% end %>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-5 mx-auto">
      <h1 class="mb-5">商品編集</h1>
        <%= form_with model: @product, url: admin_product_path, local: true do |f| %>
          <%= render "form_products", f: f %>

          <%= f.submit '編集する', class: "btn btn-success btn-lg pull-right d-block mx-auto" %>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-9 mx-auto">
        <h1>商品一覧</h1>
        <%= link_to icon("fas", "plus-circle", "新規登録"), new_admin_product_path, class: "float-right" %>
        <table class="table table-hover table-bordered table-condensed">
          <thead class="thead-dark">
            <tr class="info">
              <th>商品ID</th>
              <th>商品名</th>
              <th>税抜価格</th>
              <th>ジャンル</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <% @products.each do |product| %>
            <tr class="info">
              <td class="table-dark col-xs-1"><%= product.id %></td>
              <td class="text-left">
                <%= link_to admin_product_path(product.id), class: "btn-link text-dark" do %>
                  <%= product.name %>
                <% end %>
              </td>
              <td "text-right col-xs-1"><%= product.price.to_s(:delimited) %></td>
              <td class="text-left col-xs-3"><%= product.genre.name %></td>
              <td class="col-xs-2">
                <% if product.is_active == true %>
                  <p class="text-success">販売中</p>
                <% elsif product.is_active == false %>
                  <p class="text-muted">販売停止中</p>
                <% end %>
             </td>
            </tr>
          <% end %>
        </table>
        <%= paginate @products %>
      </div>
  </div>

app/views/admin/products/new.html.erb
<div class="text-danger">
<% if @product.errors.any? %>
   <span class="h4"><%= @product.errors.count %>errors prohibited this obj from being saved:</span>
  <% @product.errors.full_messages.each do |message| %><br>
     ・<%= message %>
  <% end %>
<% end %>
</div>
<div class="container">
  <div class="row">
    <div class="mx-auto col-md-5">
      <h1 class="mb-5">商品新規登録</h1>
        <%= form_with model: @product, url: admin_products_path, local: true do |f| %>
         <%= render "form_products", f: f %>
          <%= f.submit '新規登録', class: "btn btn-success btn-lg mx-auto d-block" %>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="container">
  <h1 >商品詳細</h1>
  <div class="row">
    <div class="mt-5 col-md-5">
        <span><%= attachment_image_tag @product, :image, format: 'jpeg', fallback: 'no_image.jpg', size:'300x200'%></sapn>
    </div>
    <div class="mt-5 col-md-5">
      <div class="row">
        <p class="col-md-4 admin-item-title">商品名:</p>
        <p class="col-md-8"><%= @product.name %></p>
      </div>
      <div class="row">
        <p class="col-md-4">商品説明:</p>
        <p class="col-md-8"><%= @product.introduction %></p>
      </div>
      <div class="row">
        <p class="col-md-4">ジャンル:</p>
        <p class="col-md-8"><%= @product.genre.name %></p>
      </div>
      <div class="row">
        <p class="col-md-4">税込価格<br>(税抜価格)</p>
        <p class="col-md-8 admin-item-price"><%= (@product.price * 1.08).to_i %>(<%= @product.price %>) 円 </P>
      </div>
      <div class="row">
        <p class="col-md-4">販売ステータス</p>
          <p class="col-md-8">
            <% if @product.is_active == true %>
              <strong><span class="text-success">販売中</span></strong>
            <% elsif @product.is_active == false %>
              <strong><span class="text-muted">販売停止中</span></strong>
            <% end %>
          </p>
      </div>
          <%= link_to "編集する", edit_admin_product_path(@product.id), class: "btn btn-success btn-lg pull-right" %>
    </div>
  </div>
</div>

app/views/admin/products/top.html.erb
<% provide(:title, "トップ") %>
<div class="container">
  <div class="row">
  	<div class="col-xs-12">
  		<h2 class="head-line title_h2 text-center">管理者画面</h2>
  		<p class="order-count">本日の注文件数
  			<span>
  				<%= link_to today_order_index_admin_orders_path, class: "btn-link" do %>
  				<%= @orders.count %>件
  				<% end %>
  			</span>
  		</p>
  	</div>
  </div>
</div>